[general]
import = ["~/.config/alacritty/themes/gruber_darker.toml"]

[window]
dynamic_title = true
padding = { x = 4, y = 2 }
opacity = 0.75
decorations = "none"

[scrolling]
history = 10000
multiplier = 5

[font]
size = 14.0
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[terminal]
shell = { program = "/opt/homebrew/bin/fish", args = [
        "-l",
        "-C",
        "tmux new-session -A -s main",
] }
