# [[plugins]]
# repo = "craftzdog/solarized-osaka.nvim"
# on_event = ['VimEnter']
# lua_source = '''
# require('solarized-osaka').setup({ })
# '''
[[plugins]]
repo = "ellisonleao/gruvbox.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("gruvbox").setup({
  contrast = "soft",
  transparent_mode = true,
  palette_overrides = {
    bright_green = "#98971a",
  },
})
"""

[[plugins]]
repo = "miyakogi/seiya.vim"
# on_event = ['BufRead', 'CursorHold']
on_event = ["ColorSchemePre", 'BufRead', 'CursorHold']
# on_cmd = ["SeiyaEnable"]
lua_source = """
vim.cmd("let g:seiya_target_groups = has('nvim') ? ['guibg'] : ['ctermbhhg']")
-- vim.g.seiya_auto_enable = 1
-- vim.cmd("SeiyaEnable")
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
lua_source = """
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  ensure_installed = 'all'
}
"""

[[plugins]]
repo = "numToStr/Comment.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('Comment').setup()
"""

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
on_event = ['VimEnter']
lua_source = """
require('lualine').setup()
"""

[[plugins]]
repo = "shortcuts/no-neck-pain.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('no-neck-pain').setup()
"""

[[plugins]]
repo = "Shougo/deol.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = '''
require("config/deol")
'''

[[plugins]]
repo = "vim-jp/vimdoc-ja"
on_event = ['BufRead', 'CursorHold']


[[plugins]]
repo = "ryicoh/deepl.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:deepl#endpoint = "https://api-free.deepl.com/v2/translate"

let g:deepl#auth_key = "8321b217-9289-4510-934e-ca5abb14fa57:fx"

vmap t<C-j> <Cmd>call deepl#v("JA")<CR>
vmap t<C-e> <Cmd>call deepl#v("EN")<CR>
'''

[[plugins]]
repo = "skanehira/translate.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let mapleader = " "
let g:translate_source = "en"
let g:translate_target = "ja"
let g:translate_popup_window = 1
nmap gr <Plug>(Translate)
vmap <leader>t <Plug>(VTranslate)
'''

[[plugins]]
repo = "machakann/vim-sandwich"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = "nvim-zh/colorful-winsep.nvim"
on_event = ['WinNew', 'WinEnter']
lua_source = '''
require('colorful-winsep').setup {
  symbols = { '─', '│', '╭', '╮', '╰', '╯' },
}
'''

[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = 'nvim-neotest/nvim-nio'
on_source = ['nvim-dap']

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = ['nvim-dap']
lua_source = '''
require('dapui').setup({
  layouts = {
    {
      elements = {
        { id = "watches", size = 0.20 },
        { id = "stacks", size = 0.20 },
        { id = "breakpoints", size = 0.20 },
        { id = "scopes", size = 0.40 }
      },
      position = "right",
      size = 40
    },
    {
      elements = {
        { id = "console", size = 0.5 },
        { id = "repl", size = 0.5 }
      },
      position = "bottom",
      size = 10
    }
  },
})
-- 自動でウィンドウを開閉
local dap, dapui = require("dap"), require("dapui")
dap.listeners.before.attach.dapui_config = function()
  dapui.open()
end
dap.listeners.before.launch.dapui_config = function()
  dapui.open()
end
dap.listeners.before.event_terminated.dapui_config = function()
  dapui.close()
end
dap.listeners.before.event_exited.dapui_config = function()
  dapui.close()
end
'''

[[plugins]]
repo = 'theHamsta/nvim-dap-virtual-text'
on_source = ['nvim-dap']
lua_source = '''
require('nvim-dap-virtual-text').setup()
'''

[[plugins]]
repo = 'mfussenegger/nvim-dap-python'
on_event = ['BufRead', 'CursorHold']
# on_source = ['nvim-dap']
lua_source = '''
require('dap-python').setup('python')
-- コンテナ上のPythonをデバッグする設定
table.insert(require('dap').configurations.python, {
  type = 'python',
  request = 'attach',
  name = 'Remote Python Debugger',
  port = 5678,
  host = "127.0.0.1",
  mode = "remote",
  cwd = vim.fn.getcwd(),
  -- ローカルとコンテナのパスをマッピング
  pathMappings = {
    {
      localRoot = function() -- ローカルのPythonコードを格納するディレクトリ
        return vim.fn.input("Local directory > ", vim.fn.getcwd(), "file")
      end,
      remoteRoot = function() -- コンテナ内のPythonコードを格納するディレクトリ
        return vim.fn.input("Container directory > ", "/code/app", "file")
      end,
    },
  },
})

-- :help dap-mappings の例に従ってキーマッピングを設定
vim.g.mapleader = " "
vim.keymap.set('n', '<leader>d', function() require('dap').continue() end)
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end)
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end)
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end)
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end)
vim.keymap.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end)
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end)
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end)
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end)
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end)
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end)
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end)
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['copilot.vim']


[[plugins]]
repo = 'CopilotC-Nvim/CopilotChat.nvim'
on_source = ['copilot.vim']
lua_source = '''
require("CopilotChat").setup {
  debug = true, -- Enable debugging
  prompts = {
        Explain = {
            prompt = "/COPILOT_EXPLAIN コードを日本語で説明してください",
            mapping = '<leader>ce',
            description = "コードの説明をお願いする",
        },
        Review = {
            prompt = '/COPILOT_REVIEW コードを日本語でレビューしてください。',
            mapping = '<leader>cr',
            description = "コードのレビューをお願いする",
        },
        Fix = {
            prompt = "/COPILOT_FIX このコードには問題があります。バグを修正したコードを表示してください。説明は日本語でお願いします。",
            mapping = '<leader>cf',
            description = "コードの修正をお願いする",
        },
        Optimize = {
            prompt = "/COPILOT_REFACTOR 選択したコードを最適化し、パフォーマンスと可読性を向上させてください。説明は日本語でお願いします。",
            mapping = '<leader>co',
            description = "コードの最適化をお願いする",
        },
        Docs = {
            prompt = "/COPILOT_GENERATE 選択したコードに関するドキュメントコメントを日本語で生成してください。",
            mapping = '<leader>cd',
            description = "コードのドキュメント作成をお願いする",
        },
        Tests = {
            prompt = "/COPILOT_TESTS 選択したコードの詳細なユニットテストを書いてください。説明は日本語でお願いします。",
            mapping = '<leader>ct',
            description = "テストコード作成をお願いする",
        },
        FixDiagnostic = {
            prompt = 'コードの診断結果に従って問題を修正してください。修正内容の説明は日本語でお願いします。',
            mapping = '<leader>cd',
            description = "コードの修正をお願いする",
            selection = require('CopilotChat.select').diagnostics,
        },
        Commit = {
            prompt =
            '実装差分に対するコミットメッセージを日本語で記述してください。',
            mapping = '<leader>cc',
            description = "コミットメッセージの作成をお願いする",
            selection = require('CopilotChat.select').gitdiff,
        },
        CommitStaged = {
            prompt =
            'ステージ済みの変更に対するコミットメッセージを日本語で記述してください。',
            mapping = '<leader>cs',
            description = "ステージ済みのコミットメッセージの作成をお願いする",
            selection = function(source)
                return require('CopilotChat.select').gitdiff(source, true)
            end,
        },
    },
}

vim.g.mapleader = " "
vim.api.nvim_set_keymap('n', '<leader>c', ':CopilotChat<CR>', {noremap = true, silent = true})

-- バッファの内容全体を使って Copilot とチャットする
function CopilotChatBuffer()
  local input = vim.fn.input("Quick Chat: ")
  if input ~= "" then
    require("CopilotChat").ask(input, { selection = require("CopilotChat.select").buffer })
  end
end

-- <leader>ccq (Copilot Chat Quick) で Copilot とチャットする
vim.api.nvim_set_keymap("n", "<leader>cb", "<cmd>lua CopilotChatBuffer()<cr>", { noremap = true, silent = true })
'''

[[plugins]]
repo = "yuratomo/w3m.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:w3m#disable_default_keymap = 1
'''

[[plugins]]
repo = "simeji/winresizer"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = "folke/noice.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("noice").setup({
  views = {
    cmdline_popup = {
      position = {
        row = "5%",
        col = "50%",
      },
      size = {
        width = "60%",
        height = "auto",
      },
      border = {
        style = "rounded",
        padding = { 0, 1 },
      },
    },
  },
})
"""

[[plugins]]
repo = "MunifTanjim/nui.nvim"
on_source = ['noice.nvim']
