[[plugins]]
repo = "ellisonleao/gruvbox.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("gruvbox").setup({
  contrast = "soft",
  transparent_mode = true,
  palette_overrides = {
    bright_green = "#98971a",
  },
})
"""

[[plugins]]
repo = "miyakogi/seiya.vim"
on_event = ["ColorSchemePre", 'BufRead', 'CursorHold']
lua_source = """
vim.cmd("let g:seiya_target_groups = has('nvim') ? ['guibg'] : ['ctermbhhg']")
-- vim.g.seiya_auto_enable = 1
-- vim.cmd("SeiyaEnable")
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
lua_source = """
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  ensure_installed = 'all'
}
"""

[[plugins]]
repo = "numToStr/Comment.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('Comment').setup()
"""

[[plugins]]
repo = "shortcuts/no-neck-pain.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('no-neck-pain').setup()
"""

[[plugins]]
repo = "Shougo/deol.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = '''
require("hooks/deol")
'''

[[plugins]]
repo = "vim-jp/vimdoc-ja"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = "skanehira/translate.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let mapleader = " "
let g:translate_source = "en"
let g:translate_target = "ja"
let g:translate_popup_window = 1
nmap gr <Plug>(Translate)
vmap <leader>t <Plug>(VTranslate)
'''

[[plugins]]
repo = "machakann/vim-sandwich"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = ['sg.nvim']

[[plugins]]
repo = "yuratomo/w3m.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:w3m#disable_default_keymap = 1
'''

[[plugins]]
repo = "simeji/winresizer"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = "folke/noice.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("noice").setup({
  views = {
    cmdline_popup = {
      position = {
        row = "5%",
        col = "50%",
      },
      size = {
        width = "60%",
        height = "auto",
      },
      border = {
        style = "rounded",
        padding = { 0, 1 },
      },
    },
  },
})
"""

[[plugins]]
repo = "MunifTanjim/nui.nvim"
on_source = ['noice.nvim']

[[plugins]]
repo = "rcarriga/nvim-notify"
on_source = ['noice.nvim']
lua_source = """
require("notify").setup({
  background_colour = "#000000",
  timeout = 2000,
})
"""

[[plugins]]
repo = "hrsh7th/nvim-insx"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("hooks/insx")
"""

[[plugins]]
repo = 'hrsh7th/nvim-automa'
on_event = ['BufRead', 'CursorHold']
lua_source = """
local automa = require('automa')
automa.setup({
  mapping = {
    ['.'] = {
      queries = {
        -- wide-range dot-repeat definition.
        automa.query_v1({ '!n(h,j,k,l)+' }),
      }
    },
  }
})
"""

[[plugins]]
repo = "lambdalisue/vim-gin"
on_event = ['BufRead', 'CursorHold']

[[plugins]]
repo = "sourcegraph/sg.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('sg').setup({
})
"""
