[[plugins]]
repo = "craftzdog/solarized-osaka.nvim"
on_event = ['VimEnter']
lua_source = '''
require('solarized-osaka').setup({ })
'''

[[plugins]]
repo = 'm4xshen/autoclose.nvim'
on_event = ['InsertEnter']
lua_source = """
require("autoclose").setup()
"""

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = ['BufRead', 'CursorHold']
lua_source = """
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
  ensure_installed = 'all'
}
"""

[[plugins]]
repo = "numToStr/Comment.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('Comment').setup()
"""

[[plugins]]
repo = "nvim-lualine/lualine.nvim"
on_event = ['VimEnter']
lua_source = """
require('lualine').setup()
"""

[[plugins]]
repo = "shortcuts/no-neck-pain.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = """
require('no-neck-pain').setup()
"""

[[plugins]]
repo = "Shougo/deol.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = '''
require("config/deol")
'''

[[plugins]]
repo = "akinsho/bufferline.nvim"
on_event = ['BufRead', 'CursorHold']
lua_source = '''
vim.opt.termguicolors = true
require("bufferline").setup({
options = {
buffer_close_icon = false,
close_icon = false
}
})
'''

[[plugins]]
repo = "vim-jp/vimdoc-ja"
on_event = ['BufRead', 'CursorHold']


[[plugins]]
repo = "ryicoh/deepl.vim"
on_event = ['BufRead', 'CursorHold']
hook_source = '''
let g:deepl#endpoint = "https://api-free.deepl.com/v2/translate"

let g:deepl#auth_key = "8321b217-9289-4510-934e-ca5abb14fa57:fx"

vmap t<C-j> <Cmd>call deepl#v("JA")<CR>
vmap t<C-e> <Cmd>call deepl#v("EN")<CR>
'''

# [[plugins]]
# repo = "folke/noice.nvim"
# on_event = ['BufRead', 'CursorHold']
# lua_source = """
# require("noice").setup()
# """
#
# [[plugins]]
# repo = "MunifTanjim/nui.nvim"
# on_source = ['noice.nvim']
