[[plugins]]
repo = 'neovim/nvim-lspconfig'
# on_event = ['BufEnter']
on_event = ['BufRead', 'CursorHold']
lua_source = """
require("hooks/lsp")
"""

[[plugins]]
repo = 'folke/lazydev.nvim'
on_source = 'nvim-lspconfig'
